auto: true
server: true
baseurl: http://www.dublinspaceinvaders.co
permalink: /:title
prose:
  rooturl: '_posts'
  media: "media"
  metadata:
    _posts:
      - name: "title"
        field:
          element: "string"
          label: "Title"
          value: "Please Change me to a the proper Title"
      - name: "image"
        field:
          element: "string"
          label: "Image"
          value: "http://www.dublincity.ie/Pages/Welcome/defaultpagecontent/images/ShortLogo.png"

